version: 2
registries:
  # Define access for a private registry
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/@iotechsystems
    token: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
updates:
  # Maintain dependencies for xpert-manager
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
